# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processing_hints.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'processing_hints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16processing_hints.proto\x12\nprocessing\"\x1e\n\x0cHintsRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\"Z\n\rHintsResponse\x12\x12\n\nchunk_size\x18\x01 \x01(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x13\n\x0b\x62\x61tch_delay\x18\x03 \x01(\x01\x12\x0c\n\x04note\x18\x04 \x01(\t2R\n\x0fProcessingHints\x12?\n\x08GetHints\x12\x18.processing.HintsRequest\x1a\x19.processing.HintsResponseB\x1aZ\x18tp3-grpc/pb;processingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing_hints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030tp3-grpc/pb;processingpb'
  _globals['_HINTSREQUEST']._serialized_start=38
  _globals['_HINTSREQUEST']._serialized_end=68
  _globals['_HINTSRESPONSE']._serialized_start=70
  _globals['_HINTSRESPONSE']._serialized_end=160
  _globals['_PROCESSINGHINTS']._serialized_start=162
  _globals['_PROCESSINGHINTS']._serialized_end=244
# @@protoc_insertion_point(module_scope)
