// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.0
// source: processing_hints.proto

package processingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HintsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *HintsRequest) Reset() {
	*x = HintsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processing_hints_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintsRequest) ProtoMessage() {}

func (x *HintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_hints_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintsRequest.ProtoReflect.Descriptor instead.
func (*HintsRequest) Descriptor() ([]byte, []int) {
	return file_processing_hints_proto_rawDescGZIP(), []int{0}
}

func (x *HintsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type HintsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkSize  int32   `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	BatchSize  int32   `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchDelay float64 `protobuf:"fixed64,3,opt,name=batch_delay,json=batchDelay,proto3" json:"batch_delay,omitempty"`
	Note       string  `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *HintsResponse) Reset() {
	*x = HintsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processing_hints_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintsResponse) ProtoMessage() {}

func (x *HintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_hints_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintsResponse.ProtoReflect.Descriptor instead.
func (*HintsResponse) Descriptor() ([]byte, []int) {
	return file_processing_hints_proto_rawDescGZIP(), []int{1}
}

func (x *HintsResponse) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *HintsResponse) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *HintsResponse) GetBatchDelay() float64 {
	if x != nil {
		return x.BatchDelay
	}
	return 0
}

func (x *HintsResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_processing_hints_proto protoreflect.FileDescriptor

var file_processing_hints_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x69, 0x6e,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x69, 0x6e, 0x67, 0x22, 0x26, 0x0a, 0x0c, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x82, 0x01, 0x0a,
	0x0d, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x32, 0x52, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x48,
	0x69, 0x6e, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x48, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x48, 0x69,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x74, 0x70, 0x33, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_processing_hints_proto_rawDescOnce sync.Once
	file_processing_hints_proto_rawDescData = file_processing_hints_proto_rawDesc
)

func file_processing_hints_proto_rawDescGZIP() []byte {
	file_processing_hints_proto_rawDescOnce.Do(func() {
		file_processing_hints_proto_rawDescData = protoimpl.X.CompressGZIP(file_processing_hints_proto_rawDescData)
	})
	return file_processing_hints_proto_rawDescData
}

var file_processing_hints_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_processing_hints_proto_goTypes = []any{
	(*HintsRequest)(nil),  // 0: processing.HintsRequest
	(*HintsResponse)(nil), // 1: processing.HintsResponse
}
var file_processing_hints_proto_depIdxs = []int32{
	0, // 0: processing.ProcessingHints.GetHints:input_type -> processing.HintsRequest
	1, // 1: processing.ProcessingHints.GetHints:output_type -> processing.HintsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_processing_hints_proto_init() }
func file_processing_hints_proto_init() {
	if File_processing_hints_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_processing_hints_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HintsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processing_hints_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HintsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_processing_hints_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processing_hints_proto_goTypes,
		DependencyIndexes: file_processing_hints_proto_depIdxs,
		MessageInfos:      file_processing_hints_proto_msgTypes,
	}.Build()
	File_processing_hints_proto = out.File
	file_processing_hints_proto_rawDesc = nil
	file_processing_hints_proto_goTypes = nil
	file_processing_hints_proto_depIdxs = nil
}
