// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: processing_hints.proto

package processingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessingHints_GetHints_FullMethodName = "/processing.ProcessingHints/GetHints"
)

// ProcessingHintsClient is the client API for ProcessingHints service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessingHintsClient interface {
	GetHints(ctx context.Context, in *HintsRequest, opts ...grpc.CallOption) (*HintsResponse, error)
}

type processingHintsClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessingHintsClient(cc grpc.ClientConnInterface) ProcessingHintsClient {
	return &processingHintsClient{cc}
}

func (c *processingHintsClient) GetHints(ctx context.Context, in *HintsRequest, opts ...grpc.CallOption) (*HintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HintsResponse)
	err := c.cc.Invoke(ctx, ProcessingHints_GetHints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingHintsServer is the server API for ProcessingHints service.
// All implementations must embed UnimplementedProcessingHintsServer
// for forward compatibility.
type ProcessingHintsServer interface {
	GetHints(context.Context, *HintsRequest) (*HintsResponse, error)
	mustEmbedUnimplementedProcessingHintsServer()
}

// UnimplementedProcessingHintsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessingHintsServer struct{}

func (UnimplementedProcessingHintsServer) GetHints(context.Context, *HintsRequest) (*HintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHints not implemented")
}
func (UnimplementedProcessingHintsServer) mustEmbedUnimplementedProcessingHintsServer() {}
func (UnimplementedProcessingHintsServer) testEmbeddedByValue()                         {}

// UnsafeProcessingHintsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessingHintsServer will
// result in compilation errors.
type UnsafeProcessingHintsServer interface {
	mustEmbedUnimplementedProcessingHintsServer()
}

func RegisterProcessingHintsServer(s grpc.ServiceRegistrar, srv ProcessingHintsServer) {
	// If the following call pancis, it indicates UnimplementedProcessingHintsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessingHints_ServiceDesc, srv)
}

func _ProcessingHints_GetHints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingHintsServer).GetHints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessingHints_GetHints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingHintsServer).GetHints(ctx, req.(*HintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessingHints_ServiceDesc is the grpc.ServiceDesc for ProcessingHints service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessingHints_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processing.ProcessingHints",
	HandlerType: (*ProcessingHintsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHints",
			Handler:    _ProcessingHints_GetHints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processing_hints.proto",
}
